# Generated by Django 4.2 on 2025-10-09 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='media_content',
        ),
        migrations.AddField(
            model_name='question',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to='question_media/audio/'),
        ),
        migrations.AddField(
            model_name='question',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='question_media/images/'),
        ),
        migrations.AddField(
            model_name='question',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='question_media/videos/'),
        ),
    ]
