# Generated by Django 4.2 on 2025-10-10 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0002_remove_question_media_content_question_audio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='unlock_radius_meters',
            field=models.PositiveIntegerField(default=50, help_text='Distance in meters within which the question is activated'),
        ),
    ]
