# Generated by Django 4.2 on 2025-10-15 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0002_remove_question_media_content_question_audio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='is_geo',
            field=models.BooleanField(default=False),
        ),
    ]
