# Generated by Django 4.2 on 2025-10-15 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0003_quiz_is_geo'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='geolocation',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
