# Generated by Django 4.2 on 2025-11-08 20:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0004_question_geolocation'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_type', models.CharField(choices=[('image', 'Image'), ('audio', 'Audio'), ('video', 'Video')], max_length=20)),
                ('file', models.FileField(upload_to='question_media/%Y/%m/')),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_files', to='quizzes.question')),
            ],
            options={
                'verbose_name': 'Question Media',
                'verbose_name_plural': 'Question Media',
                'ordering': ['display_order', 'uploaded_at'],
            },
        ),
    ]
