# Generated by Django 4.2 on 2025-11-09 14:25

from django.db import migrations, models
import quizzes.models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0005_questionmedia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionmedia',
            name='file',
            field=models.FileField(upload_to=quizzes.models.question_media_upload_path),
        ),
    ]
