# Generated by Django 4.2 on 2025-11-10 16:24

from django.db import migrations, models
import quizzes.validators


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0007_quiz_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to='question_media/audio/', validators=[quizzes.validators.validate_audio_file]),
        ),
        migrations.AlterField(
            model_name='question',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='question_media/images/', validators=[quizzes.validators.validate_image_file]),
        ),
        migrations.AlterField(
            model_name='question',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='question_media/videos/', validators=[quizzes.validators.validate_video_file]),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='quiz_images/', validators=[quizzes.validators.validate_image_file]),
        ),
    ]
