# Generated by Django 4.2 on 2025-11-11 09:09

from django.db import migrations, models
import django.db.models.deletion
import quizzes.validators


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0008_alter_question_audio_alter_question_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='question_media/images/', validators=[quizzes.validators.validate_question_image]),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='quiz_images/', validators=[quizzes.validators.validate_quiz_image]),
        ),
        migrations.CreateModel(
            name='Hint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hint_text', models.TextField(blank=True)),
                ('hint_image', models.ImageField(blank=True, null=True, upload_to='question_media/hints/images/', validators=[quizzes.validators.validate_question_image])),
                ('hint_audio', models.FileField(blank=True, null=True, upload_to='question_media/hints/audio/', validators=[quizzes.validators.validate_audio_file])),
                ('hint_video', models.FileField(blank=True, null=True, upload_to='question_media/hints/videos/', validators=[quizzes.validators.validate_video_file])),
                ('points_penalty', models.PositiveIntegerField(help_text='Points deducted when hint is unlocked')),
                ('hint_order', models.PositiveIntegerField(help_text='Display order (1, 2, or 3)')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hints', to='quizzes.question')),
            ],
            options={
                'ordering': ['hint_order'],
                'unique_together': {('question', 'hint_order')},
            },
        ),
        migrations.CreateModel(
            name='HintUnlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unlocked_at', models.DateTimeField(auto_now_add=True)),
                ('points_deducted', models.PositiveIntegerField(help_text='Points deducted when unlocked')),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unlocked_hints', to='quizzes.quizattempt')),
                ('hint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unlocks', to='quizzes.hint')),
            ],
            options={
                'ordering': ['unlocked_at'],
                'unique_together': {('attempt', 'hint')},
            },
        ),
    ]
