# Generated by Django 4.2 on 2025-11-18 08:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0009_alter_question_image_alter_quiz_image_hint_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('en', 'English'), ('ru', 'Russian'), ('sr', 'Serbian')], max_length=5)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='quizzes.quiz')),
            ],
            options={
                'verbose_name': 'Quiz Translation',
                'verbose_name_plural': 'Quiz Translations',
                'unique_together': {('quiz', 'language')},
            },
        ),
        migrations.CreateModel(
            name='QuestionTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('en', 'English'), ('ru', 'Russian'), ('sr', 'Serbian')], max_length=5)),
                ('question_text', models.TextField()),
                ('correct_answer', models.TextField(blank=True, null=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='quizzes.question')),
            ],
            options={
                'verbose_name': 'Question Translation',
                'verbose_name_plural': 'Question Translations',
                'unique_together': {('question', 'language')},
            },
        ),
        migrations.CreateModel(
            name='OptionTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('en', 'English'), ('ru', 'Russian'), ('sr', 'Serbian')], max_length=5)),
                ('option_text', models.CharField(max_length=500)),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='quizzes.option')),
            ],
            options={
                'verbose_name': 'Option Translation',
                'verbose_name_plural': 'Option Translations',
                'unique_together': {('option', 'language')},
            },
        ),
        migrations.CreateModel(
            name='HintTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('en', 'English'), ('ru', 'Russian'), ('sr', 'Serbian')], max_length=5)),
                ('hint_text', models.TextField()),
                ('hint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='quizzes.hint')),
            ],
            options={
                'verbose_name': 'Hint Translation',
                'verbose_name_plural': 'Hint Translations',
                'unique_together': {('hint', 'language')},
            },
        ),
    ]
