# Generated by Django 4.2 on 2025-11-18 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0010_quiztranslation_questiontranslation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='default_language',
            field=models.CharField(choices=[('en', 'English'), ('ru', 'Russian'), ('sr', 'Serbian')], default='en', help_text='Primary language of quiz content', max_length=5),
        ),
    ]
