# Generated by Django 5.2.8 on 2025-11-21 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0011_quiz_default_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='thumbnail',
            field=models.ImageField(blank=True, editable=False, null=True, upload_to='quiz_thumbnails/'),
        ),
    ]
