# Generated by Django 5.2.8 on 2025-11-21 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0012_quiz_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionmedia',
            name='thumbnail',
            field=models.ImageField(blank=True, editable=False, null=True, upload_to='question_media/thumbnails/'),
        ),
    ]
