# Generated by Django 4.2 on 2025-11-10 16:24

from django.db import migrations, models
import quizzes.validators


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customuser_bio_customuser_profile_picture_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures/', validators=[quizzes.validators.validate_profile_picture]),
        ),
    ]
