# Generated by Django 5.2.8 on 2025-11-28 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_customuser_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='profile_thumbnail',
            field=models.ImageField(blank=True, editable=False, null=True, upload_to='profile_thumbnails/'),
        ),
    ]
